"""初始化

Revision ID: e02a3c277302
Revises: 
Create Date: 2021-02-21 19:51:54.465792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e02a3c277302'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Admin',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sno', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', 'sno')
    )
    op.create_table('Course',
    sa.Column('sno', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('sno')
    )
    op.create_table('Student',
    sa.Column('sno', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('classes', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('sno')
    )
    op.create_table('Teacher',
    sa.Column('sno', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('office', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('sno')
    )
    op.create_table('Tools',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sno', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sno')
    )
    op.create_table('Booking_student',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('course_sno', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['course_sno'], ['Course.sno'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Student_Course',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_sno', sa.String(length=20), nullable=True),
    sa.Column('Course_sno', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['Course_sno'], ['Course.sno'], ),
    sa.ForeignKeyConstraint(['student_sno'], ['Student.sno'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Teacher_Course',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('teacher_sno', sa.String(length=20), nullable=True),
    sa.Column('Course_sno', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['Course_sno'], ['Course.sno'], ),
    sa.ForeignKeyConstraint(['teacher_sno'], ['Teacher.sno'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Teacher_Course')
    op.drop_table('Student_Course')
    op.drop_table('Booking_student')
    op.drop_table('Tools')
    op.drop_table('Teacher')
    op.drop_table('Student')
    op.drop_table('Course')
    op.drop_table('Admin')
    # ### end Alembic commands ###
